### ISSUE TITLE
$p->getInventory()->getItemInHand() on null

### ISSUE THREAD

**Issue by Awzaw** [LDX-MCPE/BanItem#2]
Hello, I'm getting the occasional: "Error: Call to a member function getItemInHand() on null" in onHurt().

Thanks!

**Comment by alex2534alex** [comment]
So, where is fix? :\

**Comment by Awzaw** [comment]
Are you using the latest version 2.2? I don't see this any more.

**Comment by alex2534alex** [comment]
So, this issue isn't closed?

**Comment by alex2534alex** [comment]
why*
